const dummyUser = {
  fullName: 'Dummy User',
  password: 'dummy password',
  identificationNumber: 'dummy id',
  homeAddress: 'dummy address',
  mobileNumber: 'dummy mobile',
  dob: 'dummy dob',
  email: 'claraadora@gmail.com',
  socialMediaPlatform: 'dummyuser123',
  photoUrl: 'dummy.jpeg',
  gender: 'dummy gender',
  citizenship: 'dummy citizenship',
  organization: 'dummy organization',
  position: 'dummy position',
  status: 'dummy status',
  role: 'dummy role',
  leadershipInterest: 'dummy interest',
  description: 'dummy description',
  interests: 'dummy interests',
  personality: 'dummy personality',
  reason: 'dummy reason',
  volunteer_length: 'dummy volunteer length',
  sessions_per_month: 123,
};

module.exports = dummyUser;
